In [1]:
import numpy as np

# Create arrays

In [2]:
some_list = [1, 2, 3]
x = np.array(some_list)
x

array([1, 2, 3])

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [4]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
m.shape

(2, 3)

In [6]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [7]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [8]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [9]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [10]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
np.diag([4, 5, 6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [14]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
p = np.ones((2, 3), int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [19]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [20]:
x + y

array([5, 7, 9])

In [21]:
x * y

array([ 4, 10, 18])

In [22]:
x ** 2

array([1, 4, 9])

Dot product of two arrays. For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b:

In [23]:
x.dot(y)

32

In [24]:
z = np.array([y, y ** 2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [25]:
z.shape

(2, 3)

In [26]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [27]:
z.T.shape

(3, 2)

In [28]:
z.dtype

dtype('int64')

In [29]:
z = z.astype('f')
z.dtype

dtype('float32')

In [30]:
a = np.array([-4, -2, 1, 3, 5])

In [31]:
a.sum(), a.max(), a.min()

(3, 5, -4)

In [32]:
a.mean()

0.59999999999999998

In [33]:
a.std()

3.2619012860600183

To find the index of a min and max value

In [34]:
a.argmin(), a.argmax()

(0, 4)

# Indexing / Slicing

In [35]:
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [36]:
s[0], s[2], s[0:3]

(0, 4, array([0, 1, 4]))

In [37]:
s[-3:]

array([100, 121, 144])

Starting third from the end to the beginning of the array and counting backwards by two:

In [38]:
s[-3::-2]

array([100,  64,  36,  16,   4,   0])

In [39]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [40]:
r[0, 0], r[0, 3], r[2, 3], r[5, 5]

(0, 3, 15, 35)

In [41]:
r[1, 3:5]

array([ 9, 10])

In [42]:
r[:2, 3:]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [43]:
r[:2, :-3]

array([[0, 1, 2],
       [6, 7, 8]])

Select every second element from the last row:

In [44]:
r[-1, ::2]

array([30, 32, 34])

Use the bracket operator to do conditional indexing and assignment. For example, return an array that is the elements of our original array that are greater than 30:

In [45]:
r[r > 30]

array([31, 32, 33, 34, 35])

This assignment will take those elements within our original array and assign to them a new value:

In [46]:
r[r > 30] = 777
r

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30, 777, 777, 777, 777, 777]])

Create a new array r2, which is a slice of the array r:

In [47]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Set all the elements of array to zero:

In [48]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

NOTE: The slice in original r has also been changed:

In [49]:
r

array([[  0,   0,   0,   3,   4,   5],
       [  0,   0,   0,   9,  10,  11],
       [  0,   0,   0,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30, 777, 777, 777, 777, 777]])

To create a copy of the r array that will not change the original array:

In [50]:
r_copy = r.copy()
r_copy

array([[  0,   0,   0,   3,   4,   5],
       [  0,   0,   0,   9,  10,  11],
       [  0,   0,   0,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30, 777, 777, 777, 777, 777]])

If we change the values of all elements in r_copy, the original array r remains unchanged:

In [51]:
r_copy[:] = 1
print(r_copy)
print()
print(r)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[  0   0   0   3   4   5]
 [  0   0   0   9  10  11]
 [  0   0   0  15  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]
 [ 30 777 777 777 777 777]]


# Iterate over arrays

Create a 4x3 array of random numbers, from zero through nine:

In [52]:
test = np.random.randint(0, 10, (4, 3))
test

array([[7, 4, 4],
       [8, 3, 8],
       [2, 2, 0],
       [6, 4, 5]])

Iterate by row:

In [53]:
for row in test:
    print(row)

[7 4 4]
[8 3 8]
[2 2 0]
[6 4 5]


Get number of rows:

In [54]:
len(test)

4

Iterate by row index by using the length function:

In [55]:
for i in range(len(test)):
    print(test[i])

[7 4 4]
[8 3 8]
[2 2 0]
[6 4 5]


Iterating by using enumerate, which return the row and index of the row:

In [56]:
for i, row in enumerate(test):
    print(i, row)

0 [7 4 4]
1 [8 3 8]
2 [2 2 0]
3 [6 4 5]


In [57]:
test2 = test ** 2
test2

array([[49, 16, 16],
       [64,  9, 64],
       [ 4,  4,  0],
       [36, 16, 25]])

To iterate through both arrays:

In [58]:
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[7 4 4] + [49 16 16] = [56 20 20]
[8 3 8] + [64  9 64] = [72 12 72]
[2 2 0] + [4 4 0] = [6 6 0]
[6 4 5] + [36 16 25] = [42 20 30]
